Repository CSPI-QE/MSI, pull requests merged in 2024-04, with the labels that each got.

#2 refactor release-it script
  poetry.lock
  pyproject.toml
  scripts/release_it_repos.py
Labels: approved, lgtm

#3 release-it script: use `run_command`
  poetry.lock
  pyproject.toml
  scripts/release_it_repos.py
Labels: approved

#6 add qe-metrics release
  REPOS_INVENTORY.md
  manifests/repositories.yaml
Labels: approved, lgtm, verified, size/XS, can-be-merged, approved-myakove, branch-main
